baseURL = "https://jthulhu.github.io/"
languageCode = "en-us"
title = "microbo"

[params]
ShowReadingTime = true
ShowCodeCopyButtons = true
ShowToc = true
hideFooter = true

[params.profileMode]
enabled = true
title = "microbo"
subtitle = "jthulhu's website"
imageUrl = "/images/scantree.png"

[params.assets]
favicon = "/favicons/favicon.ico"
favicon16x16 = "/favicons/favicon-16x16.png"
favicon32x32 = "/favicons/favicon-32x32.png"

[outputs]
home = ["HTML", "RSS", "JSON"]

[markup.goldmark.extensions.passthrough]
enable = true
delimiters = { block = [['\[', '\]']], inline = [['\(', '\)']] }

[markup.goldmark.renderer]
unsafe = true

[[menu.main]]
  identifier = "blog"
  name = "Blog"
  url = "/blog"
  weight = 10

[[menu.main]]
  identifier = "about-me"
  name = "About Me"
  url = "/about-me"
  weight = 20

[[menu.main]]
  identifier = "search"
  name = "Search"
  url = "/search"
  weight = 30

[[menu.main]]
  identifier = "tags"
  name = "Tags"
  url = "/tags"
  weight = 40

[[module.imports]]
  path = "github.com/adityatelange/hugo-PaperMod"
